# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70f9d17046bafa03425515f381d4a193f083cdc2ad1b24f2201db50ecf98dc9380db11948c7e9ddaf639d6427e424302a39d318fc991c932b31a00f38cfdd67

test:
  secret_key_base: 79f63edee624f6cae4bbef943200e573b9eb299db5924d2f5e4e38a271b81cd9f4033f8dff257e2eb8499d55920c67e0474501c146e288a75170b8f4e863bd9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
